### ISSUE TITLE
Petits ajustements

### ISSUE THREAD

**Issue by arnaudlevy** [noesya/rancoper-site#1]
- [x] Mettre la barre du haut en vert idem hero sur mobile
- [x] Soit aligner le souligné sous les icônes de lien externe, soit le supprimer (juste sous l'icône)
- [x] Dans le CTA les soulignements des liens sont trop visibles, faire qqch de plus subtil
- [x] En mobile l'ouverture du menu devrait bloquer le scroll (pour tout le thème)
- [x] réparer le fil d'Ariane mobile https://ran-coper.fr/toutes-les-actualites/2021-05-15-tout-savoir-sur-la-reforme-2021-des-cahiers-des-clauses-administratives-generales-ccag/

**Comment by alexisben** [comment]
Pas tout compris, on en cause ?

**Comment by arnaudlevy** [comment]
Point 2 https://ran-coper.fr/a-propos/presentation/

**Comment by arnaudlevy** [comment]
![image](https://user-images.githubusercontent.com/2088968/221189490-e1fb7d1f-1de6-419b-8cd0-da0225466d0d.png)

**Comment by arnaudlevy** [comment]
<img width="395" alt="image" src="https://user-images.githubusercontent.com/2088968/221189749-e0c585d5-8851-4a3e-831d-7c229c97afc0.png">

**Comment by alexisben** [comment]
Pour l'icône lien externe sur iOS : 

- Soit j'enlève l'inline pour ne pas souligner l'élément, mais dans ce cas, le picto peut chasser à la ligne :

![image](https://user-images.githubusercontent.com/4630530/221194189-c37b5065-6e7c-4ccf-b060-ec3dea9127e1.png)

- Soit j'aligne en baseline le picto, mais à cause de l'espace vide autour du picto ça le décale : 

![image](https://user-images.githubusercontent.com/4630530/221194503-a21ac556-1cab-406c-9e6e-7dd7be0b6c6d.png)

- Soit (mais pas une mince affaire) on abandonne les espaces vides des pictos dans la typo : 

<img width="118" alt="image" src="https://user-images.githubusercontent.com/4630530/221194741-4a977e5a-be46-433d-9a6f-6f27f1849a71.png">
