### ISSUE TITLE
Alignements breadcrumb

### ISSUE THREAD

**Issue by Violenn** [noesya/rancoper-site#2]
Hello !

pour les pages detail aligner le haut du bloc titre sur l'image et le breadcrumb sur le bas. Tronquer si trop long comme illustré ci-dessous : 
![Capture d’écran 2023-02-23 à 14 40 18](https://user-images.githubusercontent.com/84067177/220923766-b16741f8-fccb-4b86-a2ff-5d922b515d1d.png)

**Comment by arnaudlevy** [comment]
C'est pas pratique ça parce que les images ont des tailles très variables

**Comment by Violenn** [comment]
maj après discussion, on part sous un breadcrumb sous l'image en full largeur.
![Capture d’écran 2023-02-23 à 15 19 28](https://user-images.githubusercontent.com/84067177/220933896-515c5d07-d7d1-4fae-ab0c-a41e3f3fdb03.png)

**Comment by arnaudlevy** [comment]
@alexisben ok ?

**Comment by alexisben** [comment]
Yes je crois que j'ai codé une option pour ça ;)

**Comment by arnaudlevy** [comment]
oui after-hero, faut juste ajouter le filet et vérifier les marges
