### ISSUE TITLE
Titrage homepage + spacings

### ISSUE THREAD

**Issue by Violenn** [noesya/rancoper-site#3]
Passer en deux niveaux de titrage pour le bloc hero de la home. H1 100px / 110%, baseline 30px.
Top et bottom spacing à agrandir légèrement aussi, voir image ci-jointe ou fichier client 
![Capture d’écran 2023-02-23 à 14 46 52](https://user-images.githubusercontent.com/84067177/220926158-3b98c3ac-65ba-470e-be05-749d1ace0179.png)

**Comment by alexisben** [comment]
Coucou @Violenn, c'est quelque part dans le figma ça ?

**Comment by alexisben** [comment]
On est bien là ?

![image](https://user-images.githubusercontent.com/4630530/221154403-d30e64f1-67f2-42e8-bfbb-312c3dbef9b9.png)

**Comment by Violenn** [comment]
Yes nickel

**Comment by alexisben** [comment]
Cool merci !
